### ISSUE TITLE
Kept crashing in Android 13

### ISSUE THREAD

**Issue by SinoAHpx** [KieronQuinn/PixelLauncherMods#115]
my device is alioth

**Comment by KieronQuinn** [comment]
Please send a log

**Comment by SinoAHpx** [comment]
'''
This information is generated from the Crash Log View application. - https://play.google.com/store/apps/details?id=com.arumcomm.crashlogviewer

Process: com.kieronquinn.app.pixellaunchermods
PID: 11801
UID: 10603
Frozen: false
Flags: 0x30c83e44
Package: com.kieronquinn.app.pixellaunchermods v250 (2.5)
Foreground: Yes
Process-Runtime: 4604044
Build: Redmi/alioth/alioth:13/TKQ1.220829.002/V14.0.4.0.TKHCNXM:user/release-keys
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Unable to create application com.kieronquinn.app.pixellaunchermods.PixelLauncherMods: org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton:'com.kieronquinn.app.pixellaunchermods.repositories.RemoteAppsRepository']'
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6811)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7914)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton:'com.kieronquinn.app.pixellaunchermods.repositories.RemoteAppsRepository']'
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:58)
	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
	at org.koin.core.registry.InstanceRegistry.createEagerInstances(InstanceRegistry.kt:96)
	at org.koin.core.registry.InstanceRegistry.createAllEagerInstances$koin_core(InstanceRegistry.kt:64)
	at org.koin.core.Koin.createEagerInstances(Koin.kt:323)
	at org.koin.core.KoinApplication.createEagerInstances(KoinApplication.kt:74)
	at org.koin.core.context.GlobalContext.startKoin(GlobalContext.kt:66)
	at org.koin.core.context.DefaultContextExtKt.startKoin(DefaultContextExt.kt:40)
	at com.kieronquinn.app.pixellaunchermods.PixelLauncherMods.onCreate(PixelLauncherMods.kt:189)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1287)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6806)
	... 9 more
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton:'com.kieronquinn.app.pixellaunchermods.repositories.IconLoaderRepository']'
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:58)
	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
	at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
	at org.koin.core.scope.Scope.get(Scope.kt:210)
	at com.kieronquinn.app.pixellaunchermods.PixelLauncherMods$repositories$1$3.invoke(PixelLauncherMods.kt:210)
	at com.kieronquinn.app.pixellaunchermods.PixelLauncherMods$repositories$1$3.invoke(PixelLauncherMods.kt:117)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
	... 23 more
Caused by: android.content.pm.PackageManager$NameNotFoundException: com.google.android.apps.nexuslauncher
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:505)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:488)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:482)
	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:2156)
	at com.kieronquinn.app.pixellaunchermods.utils.extensions.Extensions_ContextKt.createPixelLauncherResources(Extensions+Context.kt:50)
	at com.kieronquinn.app.pixellaunchermods.repositories.IconLoaderRepositoryImpl.<init>(IconLoaderRepository.kt:112)
	at com.kieronquinn.app.pixellaunchermods.repositories.IconLoaderRepositoryImpl.<init>(IconLoaderRepository.kt:90)
	at com.kieronquinn.app.pixellaunchermods.PixelLauncherMods$repositories$1$5.invoke(PixelLauncherMods.kt:119)
	at com.kieronquinn.app.pixellaunchermods.PixelLauncherMods$repositories$1$5.invoke(PixelLauncherMods.kt:119)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
	... 35 more

'''

**Comment by KieronQuinn** [comment]
You don't have the Pixel Launcher installed
