### ISSUE TITLE
App crashes on startup, Trebuchet

### ISSUE THREAD

**Issue by ardx812** [KieronQuinn/PixelLauncherMods#94]
Hi, I tried to use this app on Trebuchet because it doesn't support custom icon packs and such features. But the app crashes on startup.
on A5 2017 (SM-A520F) 
on LineageOS 13 
Here is the crash log:
java.lang.RuntimeException: Unable to create application com.kieronquinn.app.pixellaunchermods.PixelLauncherMods: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'com.kieronquinn.app.pixellaunchermods.repositories.RemoteAppsRepository']
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6764)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'com.kieronquinn.app.pixellaunchermods.repositories.RemoteAppsRepository']
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
	at org.koin.core.registry.InstanceRegistry.createEagerInstances(InstanceRegistry.kt:91)
	at org.koin.core.registry.InstanceRegistry.createAllEagerInstances$koin_core(InstanceRegistry.kt:54)
	at org.koin.core.Koin.createEagerInstances(Koin.kt:348)
	at org.koin.core.KoinApplication.createEagerInstances(KoinApplication.kt:74)
	at org.koin.core.context.GlobalContext.startKoin(GlobalContext.kt:66)
	at org.koin.core.context.DefaultContextExtKt.startKoin(DefaultContextExt.kt:31)
	at com.kieronquinn.app.pixellaunchermods.PixelLauncherMods.onCreate(PixelLauncherMods.kt:162)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6759)
	... 9 more
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'com.kieronquinn.app.pixellaunchermods.repositories.IconLoaderRepository']
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
	at org.koin.core.scope.Scope.resolveValue(Scope.kt:255)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:242)
	at org.koin.core.scope.Scope.get(Scope.kt:205)
	at com.kieronquinn.app.pixellaunchermods.PixelLauncherMods$repositories$1$3.invoke(PixelLauncherMods.kt:183)
	at com.kieronquinn.app.pixellaunchermods.PixelLauncherMods$repositories$1$3.invoke(PixelLauncherMods.kt:90)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
	... 23 more
Caused by: android.content.pm.PackageManager$NameNotFoundException: com.google.android.apps.nexuslauncher
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:516)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:499)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:493)
	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:2059)
	at com.kieronquinn.app.pixellaunchermods.utils.extensions.Extensions_ContextKt.createPixelLauncherResources(Extensions+Context.kt:39)
	at com.kieronquinn.app.pixellaunchermods.repositories.IconLoaderRepositoryImpl.<init>(IconLoaderRepository.kt:94)
	at com.kieronquinn.app.pixellaunchermods.repositories.IconLoaderRepositoryImpl.<init>(IconLoaderRepository.kt:72)
	at com.kieronquinn.app.pixellaunchermods.PixelLauncherMods$repositories$1$5.invoke(PixelLauncherMods.kt:92)
	at com.kieronquinn.app.pixellaunchermods.PixelLauncherMods$repositories$1$5.invoke(PixelLauncherMods.kt:92)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
	... 35 more

**Comment by KieronQuinn** [comment]
Trebuchet is not the Pixel Launcher, and thus it's not supported. I'm not sure what you expected.

That log is telling you that the Pixel Launcher isn't installed.
